export const HEADINGS = {
  // ── Universal ──
  GOAL: 'GOAL',
  CONTEXT: 'CONTEXT',
  CONSTRAINTS: 'CONSTRAINTS',
  ASSUMPTIONS: 'ASSUMPTIONS',
  RISKS: 'RISKS',
  NEXT_STEP: 'NEXT_STEP',

  // ── Workflow ──
  WORKFLOW_STAGES: 'WORKFLOW_STAGES',
  STAGE_PROMPT: 'STAGE_PROMPT',
  STAGE_PROMPT_LOW_COST: 'STAGE_PROMPT_LOW_COST',
  EXPECTED_ARTIFACTS: 'EXPECTED_ARTIFACTS',
  SUGGESTED_FIRST_STEP: 'SUGGESTED_FIRST_STEP',
  PREREQUISITES: 'PREREQUISITES',

  // ── Prompt Refinement ──
  FINAL_PROMPT: 'FINAL_PROMPT',
  CHEAPER_VARIANT: 'CHEAPER_VARIANT',
  DIAGNOSIS: 'DIAGNOSIS',
  ASSUMPTIONS_ADDED: 'ASSUMPTIONS_ADDED',
  SUGGESTED_PINNED_FACTS: 'SUGGESTED_PINNED_FACTS',

  // ── Requirement ──
  OBJECTIVE: 'OBJECTIVE',
  MUST_HAVE: 'MUST_HAVE',
  NICE_TO_HAVE: 'NICE_TO_HAVE',
  KNOWN_CONSTRAINTS: 'KNOWN_CONSTRAINTS',
  UNKNOWN_QUESTIONS: 'UNKNOWN_QUESTIONS',
  DELIVERABLES: 'DELIVERABLES',

  // ── Research ──
  EXISTING_CONTEXT: 'EXISTING_CONTEXT',
  KEY_MODULES: 'KEY_MODULES',
  RELEVANT_PATTERNS: 'RELEVANT_PATTERNS',
  BOUNDARIES: 'BOUNDARIES',
  GAPS: 'GAPS',
  RESEARCH_SUMMARY: 'RESEARCH_SUMMARY',

  // ── Discussion ──
  PROBLEM_FRAMING: 'PROBLEM_FRAMING',
  CANDIDATE_APPROACHES: 'CANDIDATE_APPROACHES',
  TRADEOFF_MATRIX: 'TRADEOFF_MATRIX',
  KEY_UNKNOWNS: 'KEY_UNKNOWNS',
  RECOMMENDED_DIRECTION: 'RECOMMENDED_DIRECTION',
  WHAT_ENTERS_PLAN: 'WHAT_ENTERS_PLAN',
  WHAT_REMAINS_OPEN: 'WHAT_REMAINS_OPEN',
  DECISION_DRAFT: 'DECISION_DRAFT',

  // ── Plan ──
  PRECONDITIONS: 'PRECONDITIONS',
  FILES_TO_MODIFY: 'FILES_TO_MODIFY',
  STEP_BY_STEP_PLAN: 'STEP_BY_STEP_PLAN',
  CODE_SKETCHES: 'CODE_SKETCHES',
  TRADEOFFS: 'TRADEOFFS',
  VERIFICATION_METHOD: 'VERIFICATION_METHOD',

  // ── Annotation Loop ──
  ANNOTATIONS_RECEIVED: 'ANNOTATIONS_RECEIVED',
  CHANGES_APPLIED: 'CHANGES_APPLIED',
  REJECTED_ANNOTATIONS: 'REJECTED_ANNOTATIONS',
  UPDATED_PLAN: 'UPDATED_PLAN',
  REMAINING_OPEN_ITEMS: 'REMAINING_OPEN_ITEMS',

  // ── Implement ──
  IMPLEMENTATION_PROMPT: 'IMPLEMENTATION_PROMPT',
  EXECUTION_CHECKLIST: 'EXECUTION_CHECKLIST',
  COMPLETION_CRITERIA: 'COMPLETION_CRITERIA',
  AGENT_INSTRUCTIONS: 'AGENT_INSTRUCTIONS',

  // ── Verify ──
  VERIFICATION_PROMPT: 'VERIFICATION_PROMPT',
  CHECKLIST: 'CHECKLIST',
  EVIDENCE_REQUIRED: 'EVIDENCE_REQUIRED',
  FAILURE_HANDLING: 'FAILURE_HANDLING',

  // ── Solidify ──
  REUSABLE_RULES: 'REUSABLE_RULES',
  MEMORY_SUMMARY: 'MEMORY_SUMMARY',
  AGENT_RULE_SUGGESTIONS: 'AGENT_RULE_SUGGESTIONS',
  LESSONS_LEARNED: 'LESSONS_LEARNED',

  // ── Compression ──
  CONFIRMED_GOALS: 'CONFIRMED_GOALS',
  CONFIRMED_CONSTRAINTS: 'CONFIRMED_CONSTRAINTS',
  ACCEPTED_DECISIONS: 'ACCEPTED_DECISIONS',
  REJECTED_OPTIONS: 'REJECTED_OPTIONS',
  OPEN_QUESTIONS: 'OPEN_QUESTIONS',
  RISKS_AND_WATCHOUTS: 'RISKS_AND_WATCHOUTS',
  CURRENT_STAGE: 'CURRENT_STAGE',
  NEXT_BEST_PROMPT: 'NEXT_BEST_PROMPT',
} as const;

export type HeadingKey = keyof typeof HEADINGS;

const ALL_HEADING_VALUES = new Set(Object.values(HEADINGS));

export function isValidHeading(heading: string): boolean {
  return ALL_HEADING_VALUES.has(heading as (typeof HEADINGS)[HeadingKey]);
}
